<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['remoteaccounts'] = 'Vzdálené účty IMAP';
$labels['account_dn'] = 'Název účtu';
$labels['account_id'] = 'Přihlašovací ID';
$labels['account_pw'] = 'Heslo';
$labels['account_pw_conf'] = 'Potvrdit heslo';
$labels['account_host'] = 'Hostitel IMAP';
$labels['add'] = 'Přidat';
$labels['back'] = 'Zrušit';
$labels['submit'] = 'Potvrdit';
$labels['archivefolder'] = 'Archiv';
$labels['remotefolders'] = 'Speciální složky';

?>