<?php

$labels = array();
$labels['remoteaccounts'] = 'Comptes IMAP distants';
$labels['account_dn'] = 'Nom du compte';
$labels['account_id'] = 'Nom d\'utilisateur';
$labels['account_pw'] = 'Mot de passe';
$labels['account_pw_conf'] = 'Confirmer le mot de passe';
$labels['account_host'] = 'Hôte IMAP';
$labels['add'] = 'Ajouter';
$labels['back'] = 'Annuler';
$labels['submit'] = 'Soumettre';
$labels['archivefolder'] = 'Archives';
$labels['remotefolders'] = 'Dossiers spéciaux';

$messages = array();
$messages['dnempty'] = 'Merci d\'entrer un nom pour ce compte';
$messages['userempty'] = 'Merci d\'entrer votre nom d\'utilisateur';
$messages['passwordempty'] = 'Merci d\'entrer un mot de passe';
$messages['passwordnotmatch'] = 'Les mots de passe ne sont pas identiques';
$messages['hostempty'] = 'Merci d\'entrer l\'adresse de l\'hôte (exemple: ssl://imap.gmail.com:993)';
$messages['accountexists'] = 'Ce compe existe déjà. Vous avez été redirigé vers le mode d\'édition.';
$messages['connectionfailed'] = 'Impossible de se connecter à l\'hôte distant.';

?>