<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Matteo Bonora <develop@matteobonora.it>                       |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['remoteaccounts'] = 'Account IMAP Remoti';
$labels['account_dn'] = 'Nome Account';
$labels['account_id'] = 'ID Accesso';
$labels['account_pw'] = 'Password';
$labels['account_pw_conf'] = 'Conferma Password';
$labels['account_host'] = 'Host IMAP';
$labels['add'] = 'Aggiungi';
$labels['back'] = 'Annulla';
$labels['submit'] = 'Invia';
$labels['archivefolder'] = 'Archivio';
$labels['remotefolders'] = 'Cartelle Speciali';

?>
