<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['remoteaccounts'] = 'Zdalne konto IMAP';
$labels['account_dn'] = 'Nazwa konta';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Hasło';
$labels['account_pw_conf'] = 'Potwierdź hasło';
$labels['account_host'] = 'IMAP host';
$labels['add'] = 'Dodaj';
$labels['back'] = 'Przerwij';
$labels['submit'] = 'Potwierdź';
$labels['archivefolder'] = 'Archiwizuj';
$labels['remotefolders'] = 'Foldery specjalne';

?>
