<?php

$labels = array();
$labels['remoteaccounts'] = 'Альтернативные учётные записи';
$labels['account_dn'] = 'Имя учётной записи';
$labels['account_id'] = 'Имя пользователя';
$labels['account_pw'] = 'Пароль';
$labels['account_pw_conf'] = 'Подтверждение пароля';
$labels['account_host'] = 'Сервер';
$labels['add'] = 'Добавить';
$labels['back'] = 'Отмена';
$labels['submit'] = 'Подтвердить';
$labels['archivefolder'] = 'Архив';
$labels['remotefolders'] = 'Особые папки';

$messages = array();
$messages['dnempty'] = 'Введите имя для этой учётной записи.';
$messages['userempty'] = 'Введите имя пользователя.';
$messages['passwordempty'] = 'Введите пароль.';
$messages['passwordnotmatch'] = 'Пароли не совпадают.';
$messages['hostempty'] = 'Введите адрес сервера (например, ssl://imap.gmail.com:993).';
$messages['accountexists'] = 'Такая учётная запись уже существует. Теперь вы редактируете её.';
$messages['connectionfailed'] = 'Не удалось соединиться с удалённым сервером.';

?>
