<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: ysliuthomas                                                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['remoteaccounts'] = '遠端IMAP帳號';
$labels['account_dn'] = '帳號名稱';
$labels['account_id'] = '登入ID';
$labels['account_pw'] = '密碼';
$labels['account_pw_conf'] = '確認密碼';
$labels['account_host'] = 'IMAP伺服器';
$labels['add'] = '新增';
$labels['back'] = '取消';
$labels['submit'] = '提交';
$labels['archivefolder'] = '封存';
$labels['remotefolders'] = '特殊資料夾';

?>