<?php

$labels = array();
$labels['remoteaccounts'] = 'Weiter IMAP Konten';
$labels['account_dn'] = 'Kontoname';
$labels['account_id'] = 'Login ID';
$labels['account_pw'] = 'Passwort';
$labels['account_pw_conf'] = 'Passwort bestätigen';
$labels['account_host'] = 'IMAP Host';
$labels['add'] = 'Hinzufügen';
$labels['back'] = 'Abbrechen';
$labels['submit'] = 'Abschicken';
$labels['archivefolder'] = 'Archiv';
$labels['remotefolders'] = 'Spezialordner';

$messages = array();
$messages['dnempty'] = 'Bitte geben Sie einen Namen für dieses Konto an';
$messages['userempty'] = 'Bitte geben Sie Ihren Login-Namen ein.';
$messages['passwordempty'] = 'Bitte geben Sie Ihr Passwort ein.';
$messages['passwordnotmatch'] = 'Das Passwort stimmt nicht überein.';
$messages['hostempty'] = 'Bitte geben Sie den IMAP-Host ein (z.B. ssl://imap.gmail.com:993).';
$messages['accountexists'] = 'Dieses Konto existiert bereits. Sie werden in den Editiermodus umgeleitet.';
$messages['connectionfailed'] = 'Verbindung konnte nicht hergestellt werden.';

?>