<?php

$labels = array();
$labels['remoteaccounts'] = 'Cuentas IMAP';
$labels['account_dn'] = 'Nombre de la cuenta';
$labels['account_id'] = 'Usuario';
$labels['account_pw'] = 'Contraseña';
$labels['account_pw_conf'] = 'Confirmar contraseña';
$labels['account_host'] = 'Servidor IMAP';
$labels['add'] = 'Agregar';
$labels['back'] = 'Cancelar';
$labels['submit'] = 'Enviar';
$labels['archivefolder'] = 'Archivo';
$labels['remotefolders'] = 'Carpetas especiales';

$messages = array();
$messages['dnempty'] = 'Ingrese un nombre para la cuenta';
$messages['userempty'] = 'Ingrese el usuario';
$messages['passwordempty'] = 'Ingrese la contraseña';
$messages['passwordnotmatch'] = 'Las contraseñas no coinciden';
$messages['hostempty'] = 'Ingrese la url del host (ej. ssl://imap.gmail.com:993)';
$messages['accountexists'] = 'La cuenta ya existe. Redireccionado a modo de edición.';
$messages['connectionfailed'] = 'Falló la conección con el servidor remoto.';

?>