<?php

$labels = array();
$labels['remoteaccounts'] = 'Externe IMAP Accounts';
$labels['account_dn'] = 'Account Naam';
$labels['account_id'] = 'Gebruikersnaam';
$labels['account_pw'] = 'Wachtwoord';
$labels['account_pw_conf'] = 'Bevestig wachtwoord';
$labels['account_host'] = 'IMAP server';
$labels['add'] = 'Toevoegen';
$labels['back'] = 'Afbreken';
$labels['submit'] = 'Bevestigen';
$labels['archivefolder'] = 'Archiveren';
$labels['remotefolders'] = 'Speciale mappen';

$messages = array();
$messages['dnempty'] = 'Geef een naam op voor dit account';
$messages['userempty'] = 'Geef een gebruikersnaam op voor dit account';
$messages['passwordempty'] = 'Geef het wachtwoord';
$messages['passwordnotmatch'] = 'Wachtwoorden komen niet overeen';
$messages['hostempty'] = 'Geef server URL (b.v. ssl://imap.gmail.com:993)';
$messages['accountexists'] = 'Dit account bestaat al. Je bent doorgestuurd naar bewerk-modus.';
$messages['connectionfailed'] = 'Kon geen verbinding opzetten met de externe server.';

?>
