<?php

$labels = array();
$labels['accounts'] = 'Weitere IMAP-Konten';
$labels['password'] = 'Passwort';
$labels['autoresponder'] = 'Abwesenheit';
$labels['forwarding'] = 'Weiterleitung';
$labels['signature'] = 'Signatur';
$labels['menu']  = 'Menue';
$labels['userinfo'] = 'Benutzer Informationen';
$labels['pwreminder'] = 'Passwort Erinnerung';
$labels['managefolders']  = 'Ordner verwalten';
$labels['account'] = 'Konto-Einstellungen';
$labels['default'] = 'Standard';
$labels['remotefolders'] = 'Spezialordner';
$labels['mycrystalmail'] = 'MyRoundCube';

?>
