<?php

$labels = array();
$labels['accounts'] = 'Remote IMAP Accounts';
$labels['password'] = 'Password';
$labels['autoresponder'] = 'Away Message';
$labels['forwarding'] = 'Message Forwarding';
$labels['spamfilter'] = 'Spam Filter';
$labels['signature'] = 'Signature';
$labels['userinfo'] = 'User Info';
$labels['pwreminder'] = 'Password Reminder';
$labels['menu']  = 'Menu';
$labels['managefolders']  = 'Manage Folders';
$labels['account'] = 'Account Administration';
$labels['default'] = 'Default';
$labels['remotefolders'] = 'Special Folders';
$labels['mycrystalmail'] = 'MyRoundCube';

?>
