<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['accounts'] = 'Удаленные учетные записи IMAP';
$labels['password'] = 'Пароль';
$labels['autoresponder'] = 'Сообщение во время отсутствия';
$labels['forwarding'] = 'Перенаправление сообщения';
$labels['spamfilter'] = 'Спам Фильтр';
$labels['signature'] = 'Подпись';
$labels['userinfo'] = 'Информация о пользователе';
$labels['pwreminder'] = 'Забыли пароль?';
$labels['menu'] = 'Меню';
$labels['managefolders'] = 'Управление папками';
$labels['account'] = 'Управление аккаунтом';
$labels['default'] = 'Настройки по умолчанию';
$labels['remotefolders'] = 'Особые папки';
$labels['mycrystalmail'] = 'МойКруглоКуб';

?>
