<?php

$labels = array();
$labels['accounts'] = '远程账号';
$labels['password'] = '修改密码';
$labels['autoresponder'] = '自动回复';
$labels['forwarding'] = '邮件转寄';
$labels['signature'] = '签名';
$labels['userinfo'] = '用户信息';
$labels['pwreminder'] = '密码提醒';
$labels['menu']  = '菜单';
$labels['managefolders']  = '管理文件夹';
$labels['account'] = '用户管理';
$labels['default'] = '默认';
$labels['remotefolders'] = '特定文件夹';

?>