<?php

$labels = array();
$labels['accounts'] = '遠程賬號';
$labels['password'] = '修改密碼';
$labels['autoresponder'] = '自動回複';
$labels['forwarding'] = '郵件轉寄';
$labels['signature'] = '簽名';
$labels['userinfo'] = '用戶信息';
$labels['pwreminder'] = '密碼提醒';
$labels['menu']  = '菜單';
$labels['managefolders']  = '管理文件夾';
$labels['account'] = '用戶管理';
$labels['default'] = '默認';
$labels['remotefolders'] = '特定文件夾';

?>