<?php

$labels = array();
$labels['accounts'] = 'Cuentas IMAP';
$labels['password'] = 'Contraseña';
$labels['autoresponder'] = 'Mensaje de ausente';
$labels['forwarding'] = 'Reenvío de mensaje';
$labels['signature'] = 'Firma';
$labels['userinfo'] = 'Información del usuario';
$labels['pwreminder'] = 'Recordar contraseña';
$labels['menu']  = 'Menú';
$labels['managefolders']  = 'Administrar carpetas';
$labels['account'] = 'Administración de cuentas';
$labels['default'] = 'Por defecto';
$labels['remotefolders'] = 'Carpetas especiales';

?>