<?php

$labels = array();
$labels['accounts'] = 'Comptes IMAP distants';
$labels['password'] = 'Mot de passe';
$labels['autoresponder'] = 'Répondeur';
$labels['forwarding'] = 'Transfert de message';
$labels['spamfilter'] = 'Filtre anti-spam';
$labels['signature'] = 'Signature';
$labels['userinfo'] = 'Info utilisateur';
$labels['pwreminder'] = 'Rappel du mot de passe';
$labels['menu']  = 'Menu';
$labels['managefolders']  = 'Gestion des dossiers';
$labels['account'] = 'Administration du compte';
$labels['default'] = 'Default';
$labels['remotefolders'] = 'Dossiers spéciaux';
$labels['mycrystalmail'] = 'MyRoundCube';

?>
