<?php

//I am aware that there is a difference between Brazilian Portuguese and Spanish but its the best we got

//Estou ciente de que há uma diferença entre o Português Brasileiro e Espanhol, mas seu o melhor que temos

$labels = array();
$labels['accounts'] = 'Cuentas IMAP';
$labels['password'] = 'Contraseña';
$labels['autoresponder'] = 'Mensaje de ausente';
$labels['forwarding'] = 'Reenvío de mensaje';
$labels['signature'] = 'Firma';
$labels['userinfo'] = 'Información del usuario';
$labels['pwreminder'] = 'Recordar contraseña';
$labels['menu']  = 'Menú';
$labels['managefolders']  = 'Administrar carpetas';
$labels['account'] = 'Administração de Contas';
$labels['default'] = 'Por defecto';
$labels['remotefolders'] = 'Carpetas especiales';

?>