<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Výchozí pohled';
$labels['time_format'] = 'Formát data';
$labels['timeslots'] = 'Slotů na hodinu';
$labels['first_day'] = 'První den v týdnu';

// calendar
$labels['calendar'] = 'Kalendář |';
$labels['day'] = 'Den';
$labels['week'] = 'Týden';
$labels['month'] = 'Měsíc';
$labels['new_event'] = 'Nová událost';
$labels['edit_event'] = 'Editovat událost';
$labels['save'] = 'Uložit';
$labels['remove'] = 'Odstranit';
$labels['cancel'] = 'Storno';
$labels['summary'] = 'Souhrn';
$labels['description'] = 'Popis';
$labels['all-day'] = 'celý den';
$labels['export'] = 'Exportovat do ICS';
$labels['category'] = 'Kategorie';
?>