<?php
/**
 * RoundCube Calendar
 *
 * Plugin to add a calendar to RoundCube.
 *
 * @version 0.2 BETA 2
 * @author Lazlo Westerhof
 * @url http://rc-calendar.lazlo.me
 * @licence GNU GPL
 * @copyright (c) 2010 Lazlo Westerhof - Netherlands
 *
 **/

$labels = array();

// config
$labels['default_view'] = 'Domyślny widok';
$labels['time_format'] = 'Format czasu';
$labels['timeslots'] = 'Przedzialy czasowe na godzinę';
$labels['first_day'] = 'Pierwszy dzień tygodnia';

// calendar
$labels['calendar'] = 'Kalendarz';
$labels['day'] = 'Dzień';
$labels['week'] = 'Tydzień';
$labels['month'] = 'Miesiąc';
$labels['new_event'] = 'Nowe zdarzenie';
$labels['edit_event'] = 'Edycja zdarzenia';
$labels['save'] = 'Zapisz';
$labels['remove'] = 'Usuń';
$labels['cancel'] = 'Anuluj';
$labels['summary'] = 'Temat';
$labels['description'] = 'Opis';
$labels['all-day'] = 'cały dzień';
$labels['export'] = 'Eksport do ICS';
$labels['category'] = 'Kategoria';
$labels['location'] = 'Lokalizacja';
?>