<?php

/*

+-----------------------------------------------------------------------+
| plugins/help/localization/ru_RU.inc                                   |
|                                                                       |
| Language file of the crystalmail help plugin                            |
| Copyright (C) 2005-2010, crystalmail Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Sergey Dukachev <iam@dukess.ru>                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['help'] = 'Помощь';
$labels['about'] = 'О программе';
$labels['license'] = 'Лицензия';

?>
