<?php

/*
+-----------------------------------------------------------------------+
| language/cs_CZ/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Ales Pospichal <ales@pospichalales.info>                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Kontakty Google';
$labels['usegoogleabook'] = 'Použít adresář Google';
$labels['googleuser'] = 'Účet Google';
$labels['googlepass'] = 'Heslo pro Google';
$labels['googlepassisset'] = 'Heslo pro Google je stále k dispozici';
$labels['googlepassisnotset'] = 'Heslo pro Google není k dispozici';

?>