<?php
$labels = array();
$labels['googlecontacts']  = 'Google Adressen';
$labels['usegoogleabook']  = 'Verwende Google-Adressbuch';
$labels['googleuser'] = 'Google Konto';
$labels['googlepass'] = 'Google Passwort';
$labels['googlepassisset'] = 'Google Passwort ist gesetzt';
$labels['googlepassisnotset'] = 'Google Passwort ist nicht gesetzt';

$messages = array();
$messages['abookreadonly'] = 'Dieses Adressbuch ist nicht editierbar.';
?>