<?php
$labels = array();
$labels['googlecontacts']  = 'Google Contacts';
$labels['usegoogleabook']  = 'Use Google address book';
$labels['googleuser'] = 'Google Account';
$labels['googlepass'] = 'Google Password';
$labels['googlepassisset'] = 'Google Password is present';
$labels['googlepassisnotset'] = 'Google Password is not present';

$messages = array();
$messages['abookreadonly'] = 'Addressbook is readonly.';
?>