<?php
$labels = array();
$labels['googlecontacts']  = 'Contactos de Google';
$labels['usegoogleabook']  = 'Usar la libreat de direciones de Google';
$labels['googleuser'] = 'Cuenta de Google';
$labels['googlepass'] = 'Contraseña de Google';
$labels['googlepassisset'] = 'La contraseña de Google está configurada';
$labels['googlepassisnotset'] = 'La contraseña de Google no está configurada';

$messages = array();
$messages['abookreadonly'] = 'La libreta de direcciones es de solo lectura.';
?>
