<?php

/*
+-----------------------------------------------------------------------+
| language/fr_FR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2010, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Contacts Google';
$labels['usegoogleabook'] = 'Utiliser le carnet d\'adresses Google';
$labels['googleuser'] = 'Compte Google';
$labels['googlepass'] = 'Mot de passe Google';
$labels['googlepassisset'] = 'Le mot de passe Google est présent';
$labels['googlepassisnotset'] = 'Le mot de passe Google est absent';

?>