<?php

/*
+-----------------------------------------------------------------------+
| language/pl_PL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Hedo77 g.rybicki|at|c2n.pl                                                              |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Kontakty Google';
$labels['usegoogleabook'] = 'Użyj książki adresowej Google';
$labels['googleuser'] = 'Konto Google';
$labels['googlepass'] = 'Hasło Google';
$labels['googlepassisset'] = 'Pokazuj hasło Google ';
$labels['googlepassisnotset'] = 'Nie pokazuj hasła Google';

?>
