<?php

/*
+-----------------------------------------------------------------------+
| language/zh_TW/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: ysliuthomas                                                   |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Google聯絡人';
$labels['usegoogleabook'] = '使用Google通訊錄';
$labels['googleuser'] = 'Google帳號';
$labels['googlepass'] = 'Google密碼';
$labels['googlepassisset'] = 'Google密碼已填寫';
$labels['googlepassisnotset'] = 'Google密碼未填寫';

?>